# uosc controls with uosc_danmaku integration
controls=menu,gap,subtitles,<has_many_audio>audio,<has_many_video>video,<has_many_edition>editions,<has_chapter>chapters,<stream>stream-quality,button:danmaku,cycle:toggle_on:show_danmaku@uosc_danmaku:on=toggle_on/off=toggle_off?Danmaku,button:danmaku_styles,button:danmaku_delay,button:danmaku_menu,gap,space,speed,space,shuffle,loop-playlist,loop-file,gap,prev,items,next,gap,fullscreen
autoload=yes
refine=sorting
time_precision=1
subtitles_directory=~~/subtitles
